version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    commit-message:
      prefix: "chore:"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    insecure-external-code-execution: allow
    target-branch: "master"
    commit-message:
      prefix: "chore:"
